### ISSUE TITLE
Syntax error in Timeout loop

### ISSUE THREAD

**Issue by xeryax** [roopesh/ad-qolsys#13]
When i was working on something else, i borked a config and got a new error -- looks to be related to the updated code.

`2021-04-27 13:29:48.413100 INFO AppDaemon: Processing restart for HASS
2021-04-27 13:29:48.413838 INFO AppDaemon: Terminating qolsys_panel
2021-04-27 13:29:48.415915 INFO AppDaemon: Initializing app qolsys_panel using class QolsysClient from module qolsys_client
2021-04-27 13:29:48.422242 WARNING qolsys_panel: ------------------------------------------------------------
2021-04-27 13:29:48.422816 WARNING qolsys_panel: Unexpected error initializing app: qolsys_panel:
2021-04-27 13:29:48.423475 WARNING qolsys_panel: ------------------------------------------------------------
2021-04-27 13:29:48.424725 WARNING qolsys_panel: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 996, in check_app_updates
    await self.init_object(app)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 315, in init_object
    modname = await utils.run_in_executor(self, __import__, app_args["module"])
  File "/usr/local/lib/python3.8/site-packages/appdaemon/utils.py", line 299, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/conf/apps/ad-qolsys/qolsys_client.py", line 3, in <module>
    import qolsys_socket
  File "/conf/apps/ad-qolsys/qolsys_socket.py", line 130
    except: TimeoutError:
                        ^
SyntaxError: invalid syntax

2021-04-27 13:29:48.425281 WARNING qolsys_panel: ------------------------------------------------------------
2021-04-27 13:29:48.426345 WARNING AppDaemon: Unable to find module qolsys_panel - initialize() skipped
`

**Comment by roopesh** [comment]
Closed in 1.7.5.1.  

Not sure how that typo got there!
