### ISSUE TITLE
Timeouts (This time with no error beforehand)

### ISSUE THREAD

**Issue by xeryax** [roopesh/ad-qolsys#14]
So... I am still getting timeouts.. but- this was interesting... you can see on the first line that the log was at 1258p, then appdaemon didnt realize it was disconnected until 2314, when i issued a command.

I wonder if there is a status command that could be sent every 60(?) minutes to check the connection, and maybe hit up a binary sensor or something if it times out?  What I am thinking, is something rudimentary to restart appdaemon if a timeout occurs?

Again, thanks for this - I love that you built this, and would love to click a "buy me a beer" button.

`2021-04-29 12:58:46.900378 INFO qolsys_panel: Publishing to: mqtt-states/binary_sensor/guest_room_window/state, Payload: Closed
2021-04-29 23:14:35.602365 INFO qolsys_panel: event: ARM
2021-04-29 23:14:35.604070 INFO qolsys_panel: event: ARM, usercode: None, partition_id: 0, arm_type: stay, instant: False
2021-04-29 23:14:35.605855 INFO qolsys_panel: armString: {'partition_id': '0', 'action': 'ARMING', 'arming_type': 'ARM_STAY', 'version': 0, 'nonce': 'qolsys', 'source': 'C4', 'version_key': 1, 'source_key': 'C4', 'token': '<<MyToken>>'}
2021-04-29 23:14:50.839066 INFO qolsys_panel: event: ARM
2021-04-29 23:14:50.842121 INFO qolsys_panel: event: ARM, usercode: None, partition_id: 0, arm_type: stay, instant: False
2021-04-29 23:14:50.845640 INFO qolsys_panel: armString: {'partition_id': '0', 'action': 'ARMING', 'arming_type': 'ARM_STAY', 'version': 0, 'nonce': 'qolsys', 'source': 'C4', 'version_key': 1, 'source_key': 'C4', 'token': '<<MyToken>>'}
2021-04-29 23:31:10.007570 ERROR qolsys_panel: qolsys socket TimeoutError: (<class 'TimeoutError'>, TimeoutError(110, 'Operation timed out'), <traceback object at 0x7fe1953e6200>)
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/conf/apps/ad-qolsys/qolsys_socket.py", line 108, in listen
    data = self._wrappedSocket.recv(8192).decode()
  File "/usr/local/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/conf/apps/ad-qolsys/qolsys_socket.py", line 133, in listen
    raise NoDataError
qolsys_socket.NoDataError`

**Comment by roopesh** [comment]
hmmm I used to run an INFO command every 5 minutes but figured it was too much unnecessary noise.  I'm look at a way to add it back in and see if it helps.

What's weird is I don't have the timeouts you're experiencing.

**Comment by roopesh** [comment]
can you comment out line 129 and 133 in qolsys_socket.py (they're both `raise NoDataError`), restart AppDaemon and see if you still have these errors?  It should be more reliable.

**Comment by xeryax** [comment]
I've had a few disconnects since I added the comment, but I am not sure what the errors looked like, as I havent had time to diagnose.

I will try and get you something tomorrow, if i can break it :)

**Comment by smwoodward** [comment]
The original C4 driver did poll the panel throughout the day. I forget how often it sent the info command. Keeping a poll every so often will also allow new sensors to automatically show up if added to the panel without needing to restart appdaemon.

**Comment by roopesh** [comment]
@xeryax try the latest build 1.8.0.2.  See if that helps you out.

**Comment by roopesh** [comment]
@xeryax did the latest resolve this issue?

**Comment by xeryax** [comment]
Im going to go ahead and say yes.... because i havent noticed any problems!

You rule!
